package com.example.android.bakingapp;

import android.content.Intent;
import android.os.Bundle;
import android.support.v4.app.LoaderManager;
import android.support.v4.content.Loader;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;

import com.example.android.bakingapp.data.Recipe;
import com.example.android.bakingapp.data.RecipeLoader;

import java.util.ArrayList;

public class MainActivity extends AppCompatActivity implements
        LoaderManager.LoaderCallbacks<ArrayList<Recipe>>,
        RecipeAdapter.RecipeAdapterOnClickHandler {

    private static final int RECIPE_LOADER = 1;

    RecyclerView mRecipesRecyclerView;
    private RecipeAdapter mRecipeAdapter;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        mRecipesRecyclerView = findViewById(R.id.rv_recipes);
        LinearLayoutManager mLayoutManager = new LinearLayoutManager(this);
        mRecipesRecyclerView.setLayoutManager(mLayoutManager);
        mRecipesRecyclerView.setHasFixedSize(true);
        mRecipeAdapter = new RecipeAdapter(this);
        mRecipesRecyclerView.setAdapter(mRecipeAdapter);
        LoaderManager loaderManager = getSupportLoaderManager();
        loaderManager.initLoader(RECIPE_LOADER, null, this).forceLoad();
    }

    /**
     * Instantiate and return a new Loader for the given ID.
     *
     * @param id   The ID whose loader is to be created.
     * @param args Any arguments supplied by the caller.
     * @return Return a new Loader instance that is ready to start loading.
     */
    @Override
    public Loader<ArrayList<Recipe>> onCreateLoader(int id, Bundle args) {
        return new RecipeLoader(this);
    }

    /**
     * Called when the loader has finished loading
     *
     * @param loader The Loader that has finished.
     * @param data   The data generated by the Loader.
     */
    @Override
    public void onLoadFinished(Loader<ArrayList<Recipe>> loader, ArrayList<Recipe> data) {
        mRecipeAdapter.swapRecipeList(data);
    }

    /**
     * Called when a previously created loader is being reset, and thus
     * making its data unavailable.  The application should at this point
     * remove any references it has to the Loader's data.
     *
     * @param loader The Loader that is being reset.
     */
    @Override
    public void onLoaderReset(Loader<ArrayList<Recipe>> loader) {

    }

    @Override
    public void onClick(Recipe recipe) {
        Intent detailsIntent = new Intent(this, DetailActivity.class);
        detailsIntent.putExtra("Recipe", recipe);
        startActivity(detailsIntent);
    }
}
